logging:
  format: JSON
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main.banner-mode: "off"

chatgpt:
  connection-timeout: 1s
  read-timeout: 1s
  write-timeout: 1s
  base-uri: https://api.openai.com/v1/engines/davinci-codex/completions