package src

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.builder.SpringApplicationBuilder

@SpringBootApplication
open class HappyHungerApplication{

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            SpringApplicationBuilder()
                .sources(HappyHungerApplication::class.java)
                .run(*args)
        }
    }
}

// /*
//  * This Kotlin source file was generated by the Gradle 'init' task.
//  */
// package src

// class HappyHungerApplication {
//     val greeting: String
//         get() {
//             return "Hello World!"
//         }
// }

// fun main() {
//     println(App().greeting)
// }
